package com.sakyone.dao;

import com.sakyone.entity.GrayHost;

public interface GrayHostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gray_host
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gray_host
     *
     * @mbggenerated
     */
    int insert(GrayHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gray_host
     *
     * @mbggenerated
     */
    int insertSelective(GrayHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gray_host
     *
     * @mbggenerated
     */
    GrayHost selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gray_host
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrayHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gray_host
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrayHost record);
}